# Generated by Django 2.2.7 on 2020-01-21 13:21

from django.db import migrations, models
import djongo.models.fields
import hmdb.submodels.metabolite
import hmdb.submodels.spectra


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Biolocation name')),
            ],
        ),
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(max_length=10, verbose_name='Version')),
                ('creation_date', models.DateTimeField(verbose_name='Creation date')),
                ('update_date', models.DateTimeField(verbose_name='Update date')),
                ('accession', models.TextField(max_length=20, verbose_name='Accession')),
                ('secondary_accessions', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.SecondaryAccession, null=True)),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('cs_description', models.TextField(max_length=1000, verbose_name='CS description')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('synonyms', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.SynonymArray, null=True)),
                ('chemical_formula', models.TextField(max_length=100, verbose_name='Chemical Formula')),
                ('average_molecular_weight', models.FloatField(verbose_name='Average molecular weight')),
                ('monisotopic_molecular_weight', models.FloatField(verbose_name='Monisotopic molecular weight')),
                ('iupac_name', models.TextField(max_length=50, verbose_name='Iupac name')),
                ('traditional_iupac', models.TextField(max_length=50, verbose_name='Traditional iupac name')),
                ('cas_registry_number', models.TextField(max_length=20, verbose_name='Cas registry number')),
                ('smiles', models.TextField(max_length=50, verbose_name='Smiles')),
                ('inchi', models.TextField(max_length=100, verbose_name='Inchi')),
                ('inchikey', models.TextField(max_length=100, verbose_name='Inchi Key')),
                ('taxonomy', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Taxonomy, null=True)),
                ('state', models.TextField(max_length=20, verbose_name='State')),
                ('experimental_properties', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.PropertyArray, null=True)),
                ('predicted_properties', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.PropertyArray, null=True)),
                ('spectra', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.SpectrumArray, null=True)),
                ('biological_properties', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.BiologicalProperties, null=True)),
                ('normal_concentrations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Concentrations, null=True)),
                ('abnormal_concentrations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Concentrations, null=True)),
                ('diseases', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Diseases, null=True)),
                ('kegg_id', models.TextField(max_length=20, verbose_name='Kegg ID')),
                ('chebi_id', models.PositiveIntegerField(verbose_name='Chebi ID')),
                ('chemspider_id', models.PositiveIntegerField(verbose_name='Chemspider ID')),
                ('pubchem_compound_id', models.PositiveIntegerField(verbose_name='Pubchem compoud ID')),
                ('foodb_id', models.PositiveIntegerField(verbose_name='Foodb ID')),
                ('drugbank_id', models.PositiveIntegerField(verbose_name='Drugbank ID')),
                ('phenol_explorer_compound_id', models.PositiveIntegerField(verbose_name='Phenol explorer compound ID')),
                ('meta_cyc_id', models.TextField(max_length=20, verbose_name='Meta cyc ID')),
                ('wikipedia_id', models.TextField(max_length=100, verbose_name='Wikipedia ID')),
                ('knapsack_id', models.TextField(max_length=20, verbose_name='Knapsack ID')),
                ('bigg_id', models.PositiveIntegerField(verbose_name='Bigg ID')),
                ('metlin_id', models.PositiveIntegerField(verbose_name='Metlin ID')),
                ('pdb_id', models.TextField(max_length=20, verbose_name='PDB ID')),
                ('synthesis_reference', models.TextField(max_length=1000, verbose_name='Synthesis reference')),
                ('general_references', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.ReferenceArray, null=True)),
                ('protein_associations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.ProteinAssociations, null=True)),
                ('biocyc_id', models.TextField(blank=True, max_length=50, verbose_name='Biocyc_id')),
                ('biospecimen_locations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Biospecimen, null=True)),
                ('cellular_locations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Cellular, null=True)),
                ('tissue_locations', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Tissue, null=True)),
                ('pathways', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.Pathway, null=True)),
                ('drugbank_metabolite_id', models.TextField(max_length=50, verbose_name='Drugbank metabolite ID')),
                ('external_links', djongo.models.fields.EmbeddedField(blank=True, model_container=hmdb.submodels.metabolite.ExternalLinks, null=True)),
                ('het_id', models.PositiveIntegerField(verbose_name='Het ID')),
                ('nugowiki', models.PositiveIntegerField(verbose_name='Nugowiki')),
                ('status', models.TextField(max_length=50, verbose_name='Status')),
                ('wikipidia', models.TextField(max_length=100, verbose_name='Wikipidia')),
            ],
        ),
        migrations.CreateModel(
            name='MetaboliteNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Metabolite name')),
                ('met_id', models.PositiveIntegerField(verbose_name='Metabolite ID')),
                ('super_class', models.TextField(max_length=100, verbose_name='Super class')),
                ('main_class', models.TextField(max_length=100, verbose_name='Class')),
                ('sub_class', models.TextField(max_length=100, verbose_name='Sub class')),
                ('biospecimen_locations', djongo.models.fields.ListField(verbose_name='Biospecimen location')),
                ('monisotopic_molecular_weight', models.FloatField(verbose_name='Monisotopic molecular weight')),
            ],
            options={
                'db_table': 'hmdb_met_names',
            },
        ),
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_ms', djongo.models.fields.EmbeddedField(model_container=hmdb.submodels.spectra.MsMs, null=True)),
            ],
        ),
    ]
