# Generated by Django 2.2.7 on 2019-12-09 22:21

from django.db import migrations, models
import djongo.models.fields
import hmdb.submodels.metabolite


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0002_metabolite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabolite',
            name='abnormal_concentrations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Concentrations, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='biological_properties',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.BiologicalProperties, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='biospecimen_locations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Biospecimen, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='cellular_locations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Cellular, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='diseases',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Diseases, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='experimental_properties',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.PropertyArray, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='external_links',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.ExternalLinks, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='general_references',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.ReferenceArray, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='name',
            field=models.TextField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='normal_concentrations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Concentrations, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='pathways',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Pathway, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='predicted_properties',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.PropertyArray, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='protein_associations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.ProteinAssociations, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='secondary_accessions',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.SecondaryAccession, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='spectra',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.SpectrumArray, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='synonyms',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.SynonymArray, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='taxonomy',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Taxonomy, null=True),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='tissue_locations',
            field=djongo.models.fields.EmbeddedModelField(blank=True, model_container=hmdb.submodels.metabolite.Tissue, null=True),
        ),
    ]
