# Generated by Django 2.2.7 on 2019-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmdb', '0003_auto_20191209_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaboliteNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Metabolite name')),
                ('met_id', models.PositiveIntegerField(verbose_name='Metabolite ID')),
            ],
            options={
                'db_table': 'hmdb_met_names',
            },
        ),
    ]
